### PR TITLE
changed socket timeout to 0 (infinity)

### PR DESCRIPTION
**Pull request by tjmehta**

### CODE REVIEW

**Comment by bkendall** [comment]
what doth this solve?

**Comment by tjmehta** [comment]
I just linked locally and it appears to work with api now. I tried this in the past and it didn't.. but could've been something else. On staging, if no data is sent on the socket for two minutes, docker-listener's stream will end and not reconnect.

**Comment by anandkumarpatel** [comment]
LGTM

**Comment by bkendall** [comment]
LGTM

**Pull request merged**
