### PR TITLE
Add TTL 30 seconds to hermes queues

### PR DESCRIPTION
**Pull request by cflynn07**

### CODE REVIEW

**Comment by podviaznikov** [comment]
Few things:
- there is task in JIRA https://runnable.atlassian.net/browse/SAN-3272
- this is going to delete a lot of important queues https://github.com/CodeNow/docker-listener/blob/master/lib/rabbitmq.js#L48
- 30 seconds is too small timeout. Deploy can go wrong (and docker-listener will not run for few minutes), network can fail etc. Timeout should be way higher imho

**Comment by cflynn07** [comment]
It looks like docker-listener only subscribes to 1 queue:

https://github.com/CodeNow/docker-listener/blob/master/lib/rabbitmq.js#L59
Ex: `10-8-192-213.docker.event.publish`

It appears to be set up to publish to these queues:
https://github.com/CodeNow/docker-listener/blob/master/lib/rabbitmq.js#L48

```
'on-instance-container-create',
      'on-instance-container-die',
      'on-image-builder-container-create',
      'on-image-builder-container-die',
      dockerEventPublishQueue
```

But there doesn't appear to be any services subscribed to those queues? (They're not listed in the rabbitmq admin queues)

This change will only affect the `dockerEventPublishQueue` ex: `10-8-192-213.docker.event.publish`
We can increase the TTL. The jobs in the `docker.event.publish` queues for each dock will be lost if docker-listener goes down for a time period greater than the TTL

**Comment by cflynn07** [comment]
Actually if could someone help explain why these queues aren't in rabbitmq on delta?

```
'on-instance-container-create',
      'on-instance-container-die',
      'on-image-builder-container-create',
      'on-image-builder-container-die',
```

**Comment by cflynn07** [comment]
Okay I failed. The pagination section of rabbitmq admin is not very user-friendly

**Comment by cflynn07** [comment]
Okay after looking into this more I see that these changes may assign TTL values to these queues:

```
'on-instance-container-create',
'on-instance-container-die',
'on-image-builder-container-create',
'on-image-builder-container-die',
```

We don't want those queues to have TTLs. HOLDING until we can come up with better solution.

**Comment by anandkumarpatel** [comment]
we kind of need this... @podviaznikov what do you think of 30min TTL or all until we can get a per queue TTL?

**Comment by podviaznikov** [comment]
I'll implement per queue TTL today

**Comment by bkendall** [comment]
@podviaznikov is this still required?

**Comment by podviaznikov** [comment]
No, closing this one. I implemented it in different way

**Pull request closed without merging**
