### PR TITLE
+queues on-image-builder-container-die, on-instance-container-die

### PR DESCRIPTION
**Pull request by cflynn07**
required with this PR https://github.com/CodeNow/api/pull/978

### CODE REVIEW

**Comment by anandkumarpatel** [comment]
code LGTM, just need to add a test for this change. 

One thing to think about, lets make sure we want to filter jobs here. I would think we would do this outside of docker-listener to make it just a dumb emitter so other services can filter as defined by their logic.

**Comment by cflynn07** [comment]
@anandkumarpatel I'm not sure which existing service other than this we would want to use to insert tasks into queues? To me, moving the queue-insertion logic out of docker listener and into some other service that listens for redis events emitted from docker-listener seems like unnecessary complexity.

Do you have a specific service in mind that will listen to redis events & queue tasks from external to docker-listener? Keep in mind this hypothetical service would have to ensure that it is the only instance of itself running and inserting tasks into the queue in response to events emitted from docker-listener via redis. (Sounds like API locks doesn't it? We just spent a ton of effort trying to escape those)

**Comment by anandkumarpatel** [comment]
I didn't mean move to redis Iwas thinking to put docker events into their own queues. Docker-listener will pipe all events to ques like "on-start" and "on-death". a suggestion so we do not have to have changes in 2 places when we want to add a new service (the use case I have is for Mavis which should know all container starts / deaths for scheduling purposes)

**Comment by cflynn07** [comment]
You're suggesting docker-listener place a task into a queue that will be picked up by a worker which will create additional tasks in other queues?

**Comment by anandkumarpatel** [comment]
Not exactly, say for api case one worker will get the container-die event run the appropriate action on it based on the type. This will work well if we are going to have a base worker which is going to be extended/inherited from based on type of job.

As for Mavis which needs to know about all containers regardless of type it can have a worker which responds to all start / death events

**Pull request merged**
