### PR TITLE
Use loadenv module

### PR DESCRIPTION
**Pull request by podviaznikov**
@rsandor created `loadenv` node module. Using it.

### CODE REVIEW

**Comment by podviaznikov** [comment]
please review

**Comment by bkendall** [comment]
out of curiosity, why do we have to require and invoke it in so many `./lib` files? it's setting global variables, shouldn't it only have to be called _once_, in theory?

**Comment by cflynn07** [comment]
@bkendall I agree. I removed it from all the lib files in https://github.com/CodeNow/docker-listener/pull/18

**Comment by anandkumarpatel** [comment]
Most likely copy paste we don't need it everywhere

**Comment by podviaznikov** [comment]
I think the original idea was to make each file independent/unit testable (don't depend on the loading of envs in the by the app.js). @cflynn07 solved this in another way using `loadenv` in each test file.

**Comment by podviaznikov** [comment]
so did we reach consensus and requiring `loadenv` in the module that uses `process.env` is the way to go?

**Pull request closed without merging**
