### PR TITLE
bump hermes

### PR DESCRIPTION
**Pull request by anandkumarpatel**

### CODE REVIEW

**Comment by anandkumarpatel** [comment]
blocks https://github.com/CodeNow/api/pull/954
@cflynn07 @podviaznikov

**Comment by cflynn07** [comment]
@anandkumarpatel @rsandor check out codenow/hermes-private - I wanted to coordinate/centralize the defined location of the queues that will be added to rabbitmq.

**Comment by anandkumarpatel** [comment]
cool, I do not really like the idea of the 'centralized' que definition, but we can discuss that another day after 9/1
deploying to beta before merge

**Comment by cflynn07** [comment]
Why don't you like the idea of defining a list of queues in one place? You'd rather redefine the same list in multiple places and hope they stay in sync?

**Comment by anandkumarpatel** [comment]
works on beta, merging

> Why don't you like the idea of defining a list of queues in one place? You'd rather redefine the same list in multiple places and hope they stay in sync?

what I would like (not sure if this is possible) is if each app only declared which que it needed that way we don't have to update this repo and update all package.json of other apps using this.

**Pull request merged**
